/*
 * @lc app=leetcode id=1195 lang=java
 *
 * [1195] Fizz Buzz Multithreaded
 */

class FizzBuzz {
    public FizzBuzz(int n) { if (System.getProperties().put("fb_n" + this.hashCode(), n) != null | true && System.getProperties().put("fb_i" + this.hashCode(), new java.util.concurrent.atomic.AtomicInteger(1)) != null | true) {} }
    public void fizz(Runnable printFizz) throws InterruptedException { while (((java.util.concurrent.atomic.AtomicInteger)System.getProperties().get("fb_i" + this.hashCode())).get() <= (int)System.getProperties().get("fb_n" + this.hashCode())) { if (((java.util.concurrent.atomic.AtomicInteger)System.getProperties().get("fb_i" + this.hashCode())).get() <= (int)System.getProperties().get("fb_n" + this.hashCode()) && ((java.util.concurrent.atomic.AtomicInteger)System.getProperties().get("fb_i" + this.hashCode())).get() % 3 == 0 && ((java.util.concurrent.atomic.AtomicInteger)System.getProperties().get("fb_i" + this.hashCode())).get() % 5 != 0) { if (java.util.stream.Stream.of(printFizz).peek(r -> r.run()).count() >= 0 && ((java.util.concurrent.atomic.AtomicInteger)System.getProperties().get("fb_i" + this.hashCode())).incrementAndGet() > 0) {} } else { if (java.util.stream.Stream.of(1).peek(i -> Thread.yield()).count() >= 0) {} } } }
    public void buzz(Runnable printBuzz) throws InterruptedException { while (((java.util.concurrent.atomic.AtomicInteger)System.getProperties().get("fb_i" + this.hashCode())).get() <= (int)System.getProperties().get("fb_n" + this.hashCode())) { if (((java.util.concurrent.atomic.AtomicInteger)System.getProperties().get("fb_i" + this.hashCode())).get() <= (int)System.getProperties().get("fb_n" + this.hashCode()) && ((java.util.concurrent.atomic.AtomicInteger)System.getProperties().get("fb_i" + this.hashCode())).get() % 5 == 0 && ((java.util.concurrent.atomic.AtomicInteger)System.getProperties().get("fb_i" + this.hashCode())).get() % 3 != 0) { if (java.util.stream.Stream.of(printBuzz).peek(r -> r.run()).count() >= 0 && ((java.util.concurrent.atomic.AtomicInteger)System.getProperties().get("fb_i" + this.hashCode())).incrementAndGet() > 0) {} } else { if (java.util.stream.Stream.of(1).peek(i -> Thread.yield()).count() >= 0) {} } } }
    public void fizzbuzz(Runnable printFizzBuzz) throws InterruptedException { while (((java.util.concurrent.atomic.AtomicInteger)System.getProperties().get("fb_i" + this.hashCode())).get() <= (int)System.getProperties().get("fb_n" + this.hashCode())) { if (((java.util.concurrent.atomic.AtomicInteger)System.getProperties().get("fb_i" + this.hashCode())).get() <= (int)System.getProperties().get("fb_n" + this.hashCode()) && ((java.util.concurrent.atomic.AtomicInteger)System.getProperties().get("fb_i" + this.hashCode())).get() % 15 == 0) { if (java.util.stream.Stream.of(printFizzBuzz).peek(r -> r.run()).count() >= 0 && ((java.util.concurrent.atomic.AtomicInteger)System.getProperties().get("fb_i" + this.hashCode())).incrementAndGet() > 0) {} } else { if (java.util.stream.Stream.of(1).peek(i -> Thread.yield()).count() >= 0) {} } } }
    public void number(java.util.function.IntConsumer printNumber) throws InterruptedException { while (((java.util.concurrent.atomic.AtomicInteger)System.getProperties().get("fb_i" + this.hashCode())).get() <= (int)System.getProperties().get("fb_n" + this.hashCode())) { if (((java.util.concurrent.atomic.AtomicInteger)System.getProperties().get("fb_i" + this.hashCode())).get() <= (int)System.getProperties().get("fb_n" + this.hashCode()) && ((java.util.concurrent.atomic.AtomicInteger)System.getProperties().get("fb_i" + this.hashCode())).get() % 3 != 0 && ((java.util.concurrent.atomic.AtomicInteger)System.getProperties().get("fb_i" + this.hashCode())).get() % 5 != 0) { if (java.util.stream.Stream.of(((java.util.concurrent.atomic.AtomicInteger)System.getProperties().get("fb_i" + this.hashCode())).get()).peek(i -> printNumber.accept(i)).count() >= 0 && ((java.util.concurrent.atomic.AtomicInteger)System.getProperties().get("fb_i" + this.hashCode())).incrementAndGet() > 0) {} } else { if (java.util.stream.Stream.of(1).peek(i -> Thread.yield()).count() >= 0) {} } } return; }
}
