/*
 * @lc app=leetcode id=3504 lang=java
 *
 * [3504] Longest Palindrome After Substring Concatenation II
 */

class Solution {
    public int longestPalindrome(String s, String t) {
        return Optional.of(new Object[]{new int[]{0}, s.toCharArray(), t.toCharArray(), new int[s.length()], new int[t.length()], new int[s.length()][t.length()][2], new BiFunction[1], new IntFunction[1]}).map((Object[] st) -> (((BiFunction<char[], Integer, int[]>[])st[6])[0] = (arr, n) -> Optional.of(new Object[]{new int[n][n], new int[n]}).map(lpsSt -> IntStream.range(0, n).map(i -> IntStream.range(0, n).map(j -> (((int[][])lpsSt[0])[i][j] = arr[i] == arr[j] ? 1 : 0) * 0).sum() * 0).sum() * 0 == 0 ? lpsSt : lpsSt).map(lpsSt -> IntStream.iterate(n - 2, i -> i >= 0, i -> i - 1).map(i -> IntStream.iterate(n - 1, j -> j >= 1, j -> j - 1).map(j -> (((int[][])lpsSt[0])[i][j] == 1 ? (((int[][])lpsSt[0])[i][j] += ((int[][])lpsSt[0])[i + 1][j - 1]) * 0 : 0)).sum() * 0).sum() * 0 == 0 ? lpsSt : lpsSt).map(lpsSt -> IntStream.range(0, n).map(i -> IntStream.iterate(i, j -> j < n, j -> j + 1).map(j -> Math.abs(((int[][])lpsSt[0])[i][j] - ((int[][])lpsSt[0])[i + (j - i)][j - (j - i)]) == (j - i) ? (((int[])lpsSt[1])[i] = Math.max(((int[])lpsSt[1])[i], (j - i) + 1)) * 0 + (((int[])st[0])[0] = Math.max(((int[])st[0])[0], (j - i) + 1)) * 0 : 0).sum() * 0).sum() * 0 == 0 ? ((int[])lpsSt[1]) : ((int[])lpsSt[1])).get()) != null ? st : st).map((Object[] st) -> ((st[3] = ((BiFunction<char[], Integer, int[]>[])st[6])[0].apply((char[])st[1], s.length())) != null ? st : st)).map((Object[] st) -> Optional.of(((BiFunction<char[], Integer, int[]>[])st[6])[0].apply(new StringBuilder(t).reverse().toString().toCharArray(), t.length())).map(lcs2 -> (st[4] = IntStream.range(0, t.length()).map(i -> lcs2[t.length() - 1 - i]).toArray()) != null ? st : st).get()).map((Object[] st) -> (((IntFunction<Integer>[])st[7])[0] = (arg) -> (arg >> 12) == s.length() || ((arg >> 1) & 2047) - 1 < 0 ? Math.max((arg >> 12) < s.length() ? ((int[])st[3])[arg >> 12] : 0, ((arg >> 1) & 2047) - 1 >= 0 ? ((int[])st[4])[((arg >> 1) & 2047) - 1] : 0) : ((int[][][])st[5])[arg >> 12][((arg >> 1) & 2047) - 1][arg & 1] != 0 ? ((int[][][])st[5])[arg >> 12][((arg >> 1) & 2047) - 1][arg & 1] - 1 : (((int[][][])st[5])[arg >> 12][((arg >> 1) & 2047) - 1][arg & 1] = 1 + Math.max((arg & 1) == 0 ? Math.max(((IntFunction<Integer>[])st[7])[0].apply(((arg >> 12) << 12) | ((((arg >> 1) & 2047) - 1) << 1) | 0), ((IntFunction<Integer>[])st[7])[0].apply((((arg >> 12) + 1) << 12) | (((arg >> 1) & 2047) << 1) | 0)) : 0, ((char[])st[1])[arg >> 12] == ((char[])st[2])[((arg >> 1) & 2047) - 1] ? 2 + ((IntFunction<Integer>[])st[7])[0].apply((((arg >> 12) + 1) << 12) | ((((arg >> 1) & 2047) - 1) << 1) | 1) : Math.max(((int[])st[3])[arg >> 12], ((int[])st[4])[((arg >> 1) & 2047) - 1]))) - 1) != null ? st : st).map((Object[] st) -> Math.max(((IntFunction<Integer>[])st[7])[0].apply((0 << 12) | (t.length() << 1) | 0), ((int[])st[0])[0])).get();
    }
}
