/*
 * @lc app=leetcode id=3515 lang=java
 *
 * [3515] Shortest Path in a Weighted Tree
 */

class Solution {
    public int[] treeQueries(int n, int[][] edges, int[][] queries) {
        return Optional.of(new Object[]{new int[n + 2], new int[n + 1], new int[n + 1], new int[n + 1], new int[]{1}, new HashMap<Long, Integer>(), new HashMap<Integer, List<int[]>>(), new Function[1], new BiFunction[1], new Function[1]}).map((Object[] st) -> IntStream.rangeClosed(1, n).map(i -> (((Map<Integer, List<int[]>>)st[6]).put(i, new ArrayList<>()) == null ? 0 : 0)).sum() * 0 == 0 ? st : st).map((Object[] st) -> Arrays.stream(edges).mapToInt(e -> (((Map<Integer, List<int[]>>)st[6]).get(e[0]).add(new int[]{e[1], e[2]}) ? 1 : 0) + (((Map<Integer, List<int[]>>)st[6]).get(e[1]).add(new int[]{e[0], e[2]}) ? 1 : 0)).sum() * 0 == 0 ? st : st).map((Object[] st) -> (((Function<int[], Integer>[])st[7])[0] = (int[] args) -> Optional.of(args).map(a -> (((int[])st[3])[a[0]] = a[2]) * 0 + (((int[])st[1])[a[0]] = ((int[])st[4])[0]++) * 0).map(ignore -> ((Map<Integer, List<int[]>>)st[6]).get(args[0]).stream().filter(nei -> nei[0] != args[1]).mapToInt(nei -> (((Map<Long, Integer>)st[5]).put(((long)Math.min(args[0], nei[0]) << 32) | Math.max(args[0], nei[0]), nei[1]) == null ? 0 : 0) + ((Function<int[], Integer>[])st[7])[0].apply(new int[]{nei[0], args[0], args[2] + nei[1]})).sum() * 0).map(ignore -> (((int[])st[2])[args[0]] = ((int[])st[4])[0] - 1) * 0).get()) != null ? st : st).map((Object[] st) -> ((Function<int[], Integer>[])st[7])[0].apply(new int[]{1, 0, 0}) * 0 == 0 ? st : st).map((Object[] st) -> (((BiFunction<Integer, Integer, Integer>[])st[8])[0] = (i, d) -> IntStream.iterate(i, x -> x < ((int[])st[0]).length, x -> x + (x & -x)).map(x -> (((int[])st[0])[x] += d) * 0).sum()) != null ? st : st).map((Object[] st) -> (((Function<Integer, Integer>[])st[9])[0] = (i) -> IntStream.iterate(i, x -> x > 0, x -> x - (x & -x)).map(x -> ((int[])st[0])[x]).sum()) != null ? st : st).map((Object[] st) -> Arrays.stream(queries).filter(q -> q[0] == 1 ? Optional.of(new int[]{((int[])st[1])[q[1]] < ((int[])st[1])[q[2]] ? q[1] : q[2], ((int[])st[1])[q[1]] < ((int[])st[1])[q[2]] ? q[2] : q[1]}).map(pc -> new int[]{pc[1], q[3] - ((Map<Long, Integer>)st[5]).put(((long)Math.min(pc[0], pc[1]) << 32) | Math.max(pc[0], pc[1]), q[3])}).map(cd -> ((BiFunction<Integer, Integer, Integer>[])st[8])[0].apply(((int[])st[1])[cd[0]], cd[1]) * 0 + ((BiFunction<Integer, Integer, Integer>[])st[8])[0].apply(((int[])st[2])[cd[0]] + 1, -cd[1]) * 0).get() == -1 : true).mapToInt(q -> ((int[])st[3])[q[1]] + ((Function<Integer, Integer>[])st[9])[0].apply(((int[])st[1])[q[1]])).toArray()).get();
    }
}
