/*
 * @lc app=leetcode id=3544 lang=java
 *
 * [3544] Subtree Inversion Sum
 */

class Solution {
    public long subtreeInversionSum(int[][] edges, int[] nums, int k) {
        return (long) Optional.of(new Object[]{new int[nums.length], new int[edges.length * 2], new int[edges.length * 2], new int[]{0}, new long[nums.length * (k + 1) * 2], new LongUnaryOperator[1], new LongBinaryOperator[1]}).map((Object[] st) -> IntStream.range(0, nums.length).map(i -> (((int[])st[0])[i] = -1) * 0).sum() == 0 ? st : st).map((Object[] st) -> IntStream.range(0, nums.length * (k + 1) * 2).mapToLong(i -> ((long[])st[4])[i] = 1L << 36).sum() * 0 == 0 ? st : st).map((Object[] st) -> Arrays.stream(edges).mapToLong(e -> (((int[])st[1])[((int[])st[3])[0]] = e[1]) * 0L + (((int[])st[2])[((int[])st[3])[0]] = ((int[])st[0])[e[0]]) * 0L + (((int[])st[0])[e[0]] = ((int[])st[3])[0]++) * 0L + (((int[])st[1])[((int[])st[3])[0]] = e[0]) * 0L + (((int[])st[2])[((int[])st[3])[0]] = ((int[])st[0])[e[1]]) * 0L + (((int[])st[0])[e[1]] = ((int[])st[3])[0]++) * 0L).sum() == 0 ? st : st).map((Object[] st) -> (((LongBinaryOperator[])st[6])[0] = (state, node) -> (state & 0xFFFFF) == 0 ? 0L : ((((int[])st[1])[(int)(state & 0xFFFFF) - 1] == (int)((state >> 20) & 0xFFFFF) - 1) ? 0L : ((LongUnaryOperator[])st[5])[0].applyAsLong(((long)((int[])st[1])[(int)(state & 0xFFFFF) - 1]) | ((node + 1) << 20) | (state & 0xFFFFFF0000000000L))) + ((LongBinaryOperator[])st[6])[0].applyAsLong(((long)((int[])st[2])[(int)(state & 0xFFFFF) - 1] + 1) | (state & 0xFFFFFFFFFFF00000L), node)) != null ? st : st).map((Object[] st) -> (((LongUnaryOperator[])st[5])[0] = p -> ((long[])st[4])[(int)(p & 0xFFFFF) * (k + 1) * 2 + (int)((p >> 40) & 0xFFFFF) * 2 + (int)((p >> 60) & 1)] != 1L << 36 ? ((long[])st[4])[(int)(p & 0xFFFFF) * (k + 1) * 2 + (int)((p >> 40) & 0xFFFFF) * 2 + (int)((p >> 60) & 1)] : (((long[])st[4])[(int)(p & 0xFFFFF) * (k + 1) * 2 + (int)((p >> 40) & 0xFFFFF) * 2 + (int)((p >> 60) & 1)] = (int)((p >> 40) & 0xFFFFF) != 0 ? (((p >> 60) & 1) == 0 ? 1L : -1L) * nums[(int)(p & 0xFFFFF)] + ((LongBinaryOperator[])st[6])[0].applyAsLong(((long)(((int[])st[0])[(int)(p & 0xFFFFF)] + 1)) | (p & 0xFFFFF00000L) | (((long)((int)((p >> 40) & 0xFFFFF) - 1)) << 40) | (((p >> 60) & 1) << 60), (p & 0xFFFFF)) : Math.max((((p >> 60) & 1) == 0 ? 1L : -1L) * nums[(int)(p & 0xFFFFF)] + ((LongBinaryOperator[])st[6])[0].applyAsLong(((long)(((int[])st[0])[(int)(p & 0xFFFFF)] + 1)) | (p & 0xFFFFF00000L) | (0L << 40) | (((p >> 60) & 1) << 60), (p & 0xFFFFF)), (((p >> 60) & 1) == 0 ? -1L : 1L) * nums[(int)(p & 0xFFFFF)] + ((LongBinaryOperator[])st[6])[0].applyAsLong(((long)(((int[])st[0])[(int)(p & 0xFFFFF)] + 1)) | (p & 0xFFFFF00000L) | (((long)((k - 1) & 0xFFFFF)) << 40) | ((1L - ((p >> 60) & 1)) << 60), (p & 0xFFFFF))))) != null ? st : st).map((Object[] st) -> ((LongUnaryOperator[])st[5])[0].applyAsLong(0L)).get();
    }
}
