/*
 * @lc app=leetcode id=3553 lang=java
 *
 * [3553] Minimum Weighted Subgraph With the Required Paths II
 */

class Solution {
    public int[] minimumWeight(int[][] edges, int[][] queries) {
        return CompletableFuture.supplyAsync(() -> Optional.of(edges.length + 1).map(n -> Optional.of(new Object[]{new int[n], new int[edges.length * 2], new int[edges.length * 2], new int[edges.length * 2], new int[]{0, 0, 1}, new int[n], new int[n], new int[n * 18], new int[n], new int[queries.length], new IntBinaryOperator[1]}).map(st -> (((IntBinaryOperator[])st[10])[0] = (u, v) -> Optional.of(new int[]{((int[])st[5])[u] < ((int[])st[5])[v] ? v : u, ((int[])st[5])[u] < ((int[])st[5])[v] ? u : v, Math.abs(((int[])st[5])[u] - ((int[])st[5])[v])}).map(nodes -> IntStream.range(0, 18).map(j -> ((nodes[2] >> j) & 1) == 1 ? (nodes[0] = ((int[])st[7])[nodes[0] * 18 + j]) * 0 : 0).sum() * 0 == 0 ? (nodes[0] == nodes[1] ? nodes[0] : (IntStream.range(0, 18).map(inv -> 17 - inv).map(j -> ((int[])st[7])[nodes[0] * 18 + j] != ((int[])st[7])[nodes[1] * 18 + j] ? (nodes[0] = ((int[])st[7])[nodes[0] * 18 + j]) * 0 + (nodes[1] = ((int[])st[7])[nodes[1] * 18 + j]) * 0 : 0).sum() * 0 == 0 ? ((int[])st[7])[nodes[0] * 18] : 0)) : 0).get()) != null ? IntStream.range(0, n).map(i -> (((int[])st[0])[i] = -1) * 0).sum() * 0 + Arrays.stream(edges).mapToInt(e -> (((int[])st[1])[((int[])st[4])[0]] = e[1]) * 0 + (((int[])st[2])[((int[])st[4])[0]] = e[2]) * 0 + (((int[])st[3])[((int[])st[4])[0]] = ((int[])st[0])[e[0]]) * 0 + (((int[])st[0])[e[0]] = ((int[])st[4])[0]++) * 0 + (((int[])st[1])[((int[])st[4])[0]] = e[0]) * 0 + (((int[])st[2])[((int[])st[4])[0]] = e[2]) * 0 + (((int[])st[3])[((int[])st[4])[0]] = ((int[])st[0])[e[1]]) * 0 + (((int[])st[0])[e[1]] = ((int[])st[4])[0]++) * 0).sum() * 0 + (((int[])st[8])[0] = 0) * 0 + IntStream.range(0, n).map(dummy -> Optional.of(((int[])st[8])[((int[])st[4])[1]++]).map(u -> IntStream.iterate(((int[])st[0])[u], e -> e != -1, e -> ((int[])st[3])[e]).map(e -> ((int[])st[1])[e] != ((int[])st[7])[u * 18] ? (((int[])st[7])[((int[])st[1])[e] * 18] = u) * 0 + (((int[])st[5])[((int[])st[1])[e]] = ((int[])st[5])[u] + 1) * 0 + ((((int[])st[6])[((int[])st[1])[e]] = ((int[])st[6])[u] + ((int[])st[2])[e]) * 0) + (((int[])st[8])[((int[])st[4])[2]++] = ((int[])st[1])[e]) * 0 : 0).sum() * 0).get()).sum() * 0 + IntStream.range(1, 18).map(j -> IntStream.range(0, n).map(i -> (((int[])st[7])[i * 18 + j] = ((int[])st[7])[((int[])st[7])[i * 18 + j - 1] * 18 + j - 1]) * 0).sum() * 0).sum() * 0 + IntStream.range(0, queries.length).map(i -> (((int[])st[9])[i] = ((int[])st[6])[queries[i][0]] + ((int[])st[6])[queries[i][1]] + ((int[])st[6])[queries[i][2]] - ((int[])st[6])[((IntBinaryOperator[])st[10])[0].applyAsInt(queries[i][0], queries[i][1])] - ((int[])st[6])[((IntBinaryOperator[])st[10])[0].applyAsInt(queries[i][1], queries[i][2])] - ((int[])st[6])[((IntBinaryOperator[])st[10])[0].applyAsInt(queries[i][2], queries[i][0])]) * 0).sum() * 0 == 0 ? (int[])st[9] : (int[])st[9] : null).get()).get()).join();
    }
}
