/*
 * @lc app=leetcode id=3594 lang=java
 *
 * [3594] Minimum Time to Transport All Individuals
 */

class Solution {
    public double minTime(int n, int k, int m, int[] time, double[] mul) {
        return (k == 1 && n > 1) ? -1.0 : CompletableFuture.supplyAsync(() -> Optional.of(IntStream.range(1, 1 << n).filter(i -> Integer.bitCount(i) <= k).toArray()).map(gMasks -> Optional.of(new Object[]{new PriorityQueue<double[]>(Comparator.<double[]>comparingDouble(s -> s[0])), new double[1 << n][m][2], gMasks, Arrays.stream(gMasks).map(i -> IntStream.range(0, n).filter(b -> (i & (1 << b)) != 0).map(b -> time[b]).max().getAsInt()).toArray(), new double[]{-1.0}}).map(st -> ((PriorityQueue<double[]>)st[0]).offer(new double[]{0.0, 0.0, 0.0, 0.0}) ? Stream.iterate(new double[]{-2.0}, res -> res[0] == -2.0, res -> Optional.ofNullable(((PriorityQueue<double[]>)st[0]).poll()).map(curr -> curr[1] == (1 << n) - 1 ? ((((double[])st[4])[0] = curr[0]) * 0 == 0 ? new double[]{-1.0} : new double[]{-1.0}) : (curr[0] > ((double[][][])st[1])[(int)curr[1]][(int)curr[2]][(int)curr[3]] && ((double[][][])st[1])[(int)curr[1]][(int)curr[2]][(int)curr[3]] != 0.0 ? new double[]{-2.0} : (curr[3] == 0.0 ? (IntStream.range(0, ((int[])st[2]).length).filter(idx -> ((int)curr[1] & ((int[])st[2])[idx]) == 0).mapToDouble(idx -> ((double[][][])st[1])[(int)curr[1] | ((int[])st[2])[idx]][((int)curr[2] + (int)(((int[])st[3])[idx] * mul[(int)curr[2]])) % m][1] == 0.0 || curr[0] + ((int[])st[3])[idx] * mul[(int)curr[2]] < ((double[][][])st[1])[(int)curr[1] | ((int[])st[2])[idx]][((int)curr[2] + (int)(((int[])st[3])[idx] * mul[(int)curr[2]])) % m][1] ? ((((double[][][])st[1])[(int)curr[1] | ((int[])st[2])[idx]][((int)curr[2] + (int)(((int[])st[3])[idx] * mul[(int)curr[2]])) % m][1] = curr[0] + ((int[])st[3])[idx] * mul[(int)curr[2]]) * 0.0 + (((PriorityQueue<double[]>)st[0]).offer(new double[]{curr[0] + ((int[])st[3])[idx] * mul[(int)curr[2]], (int)curr[1] | ((int[])st[2])[idx], ((int)curr[2] + (int)(((int[])st[3])[idx] * mul[(int)curr[2]])) % m, 1.0}) ? 0.0 : 0.0)) : 0.0).sum() * 0 == 0 ? new double[]{-2.0} : new double[]{-2.0}) : (IntStream.range(0, n).filter(i -> ((int)curr[1] & (1 << i)) != 0).mapToDouble(i -> ((double[][][])st[1])[(int)curr[1] ^ (1 << i)][((int)curr[2] + (int)(time[i] * mul[(int)curr[2]])) % m][0] == 0.0 || curr[0] + time[i] * mul[(int)curr[2]] < ((double[][][])st[1])[(int)curr[1] ^ (1 << i)][((int)curr[2] + (int)(time[i] * mul[(int)curr[2]])) % m][0] ? ((((double[][][])st[1])[(int)curr[1] ^ (1 << i)][((int)curr[2] + (int)(time[i] * mul[(int)curr[2]])) % m][0] = curr[0] + time[i] * mul[(int)curr[2]]) * 0.0 + (((PriorityQueue<double[]>)st[0]).offer(new double[]{curr[0] + time[i] * mul[(int)curr[2]], (int)curr[1] ^ (1 << i), ((int)curr[2] + (int)(time[i] * mul[(int)curr[2]])) % m, 0.0}) ? 0.0 : 0.0)) : 0.0).sum() * 0 == 0 ? new double[]{-2.0} : new double[]{-2.0})))).orElse(new double[]{-1.0})).count() * 0 == 0 ? ((double[])st[4])[0] : ((double[])st[4])[0] : -1.0).get()).get()).join();
    }
}
