/*
 * @lc app=leetcode id=3883 lang=java
 *
 * [3883] Count Non Decreasing Arrays With Given Digit Sums
 */

class Solution {
    public int countArrays(int[] digitSum) {
        return Optional.of(new Object[]{new int[55][], new int[55], new int[6], new int[550], new int[550], new IntUnaryOperator[1], new Object[1]}).map((Object[] st) -> IntStream.rangeClosed(0, 5000).map(v -> (((int[])st[1])[IntStream.iterate(v, t -> t > 0, t -> t / 10).map(t -> t % 10).sum()]++) * 0).sum() == 0 ? st : st).map((Object[] st) -> IntStream.range(0, 55).map(d -> ((((int[][])st[0])[d] = new int[((int[])st[1])[d]]) != null ? 0 : 0) + ((((int[])st[1])[d] = 0) * 0)).sum() == 0 ? st : st).map((Object[] st) -> IntStream.rangeClosed(0, 5000).map(v -> Optional.of(IntStream.iterate(v, t -> t > 0, t -> t / 10).map(t -> t % 10).sum()).map(d -> ((((int[][])st[0])[d][((int[])st[1])[d]++] = v) * 0)).get()).sum() == 0 ? st : st).map((Object[] st) -> (((IntUnaryOperator[])st[5])[0] = (dummy) -> (((int[])st[2])[3] >= ((int[][])st[0])[((int[])st[2])[5]].length) ? 0 : ((((int[])st[2])[1] < ((int[][])st[0])[((int[])st[2])[4]].length && ((int[][])st[0])[((int[])st[2])[4]][((int[])st[2])[1]] <= ((int[][])st[0])[((int[])st[2])[5]][((int[])st[2])[3]]) ? ((((int[])st[2])[2] = (((int[])st[2])[2] + ((int[])st[3])[((int[])st[2])[1]]) % 1_000_000_007) * 0) + ((((int[])st[2])[1]++) * 0) + ((IntUnaryOperator[])st[5])[0].applyAsInt(0) : ((((int[])st[4])[((int[])st[2])[3]] = ((int[])st[2])[2]) * 0) + ((((int[])st[2])[3]++) * 0) + ((IntUnaryOperator[])st[5])[0].applyAsInt(0))) != null ? st : st).map((Object[] st) -> (digitSum[0] > 54 || ((int[][])st[0])[digitSum[0]].length == 0) ? ((((int[])st[2])[0] = 1) * 0 == 0 ? st : st) : IntStream.range(0, ((int[][])st[0])[digitSum[0]].length).map(idx -> (((int[])st[3])[idx] = 1) * 0).sum() == 0 ? st : st).map((Object[] st) -> IntStream.range(1, digitSum.length).map(i -> ((int[])st[2])[0] == 1 ? 0 : (digitSum[i] > 54 || ((int[][])st[0])[digitSum[i]].length == 0) ? ((((int[])st[2])[0] = 1) * 0) : ((((int[])st[2])[4] = digitSum[i - 1]) * 0) + ((((int[])st[2])[5] = digitSum[i]) * 0) + ((((int[])st[2])[1] = 0) * 0) + ((((int[])st[2])[2] = 0) * 0) + ((((int[])st[2])[3] = 0) * 0) + ((IntUnaryOperator[])st[5])[0].applyAsInt(0) * 0 + ((((Object[])st[6])[0] = st[3]) != null ? 0 : 0) + ((st[3] = st[4]) != null ? 0 : 0) + ((st[4] = ((Object[])st[6])[0]) != null ? 0 : 0)).sum() == 0 ? st : st).map((Object[] st) -> ((int[])st[2])[0] == 1 ? 0 : IntStream.range(0, ((int[][])st[0])[digitSum[digitSum.length - 1]].length).map(idx -> ((int[])st[3])[idx]).reduce(0, (a, b) -> (a + b) % 1_000_000_007)).get();
    }
}
