name: Trigger Gitlab Pipeline
on:
  workflow_dispatch: # Manual trigger
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


permissions:
  contents: write    # Needed to read/write code
  actions: write     # Mandatory to trigger/manage workflows
  statuses: write    # Optional: to update commit checkmarks

jobs:
  trigger-gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Call GitLab Trigger API
        run: |
          curl -X POST \
            -F token=${{ secrets.GITLAB_FIRST_REPO_TOKEN }} \
            -F ref=main \
            "https://gitlab.com/api/v4/projects/69610523/trigger/pipeline"

      - name: Install and Trigger GitLab Pipeline
        env:
          # Required: Personal/Project Access Token with 'api' scope
          GITLAB_TOKEN: ${{ secrets.GITLAB_FULL_API_TOKEN }}
        run: |
          # 1. Download the specific .deb package
          curl -LO https://gitlab.com/gitlab-org/cli/-/releases/v1.90.0/downloads/glab_1.90.0_linux_amd64.deb
          
          # 2. Install the package
          sudo dpkg -i glab_1.90.0_linux_amd64.deb
          
          # 3. Trigger the pipeline
          glab ci run -R "sreegithub19/first_repo" -b main